//! `myzig adopt` — summarize a tree and propose an editable migration policy.

const std = @import("std");
const check_mod = @import("check.zig");
const compat = @import("compat.zig");
const baseline = @import("baseline.zig");

pub const policy_path = ".myzig/policy.md";

pub const Summary = struct {
    zig_files: usize = 0,
    findings: usize = 0,
    ptrcast_sites: usize = 0,
    aligncast_sites: usize = 0,
    bitcast_sites: usize = 0,
};

pub fn countTree(io: compat.Io, gpa: std.mem.Allocator, path: []const u8) !Summary {
    var summary: Summary = .{};
    const st = try compat.statFile(io, path);
    switch (st.kind) {
        .file => {
            if (std.mem.endsWith(u8, path, ".zig")) {
                summary.zig_files = 1;
                try accumulateFile(io, gpa, path, &summary);
            }
        },
        .directory => try walkDir(io, gpa, path, &summary),
        else => return error.UnsupportedPath,
    }
    return summary;
}

fn walkDir(io: compat.Io, gpa: std.mem.Allocator, path: []const u8, summary: *Summary) !void {
    const names = try compat.listDirAlloc(io, gpa, path);
    defer compat.freeDirList(gpa, names);

    for (names) |name| {
        if (std.mem.eql(u8, name, ".git") or
            std.mem.eql(u8, name, ".zig-cache") or
            std.mem.eql(u8, name, "zig-cache") or
            std.mem.eql(u8, name, "zig-out") or
            std.mem.eql(u8, name, ".myzig") or
            std.mem.eql(u8, name, ".planning"))
        {
            continue;
        }
        const child = try std.fs.path.join(gpa, &.{ path, name });
        defer gpa.free(child);
        const st = compat.statFile(io, child) catch continue;
        switch (st.kind) {
            .directory => try walkDir(io, gpa, child, summary),
            .file => {
                if (std.mem.endsWith(u8, name, ".zig")) {
                    summary.zig_files += 1;
                    try accumulateFile(io, gpa, child, summary);
                }
            },
            else => {},
        }
    }
}

fn accumulateFile(io: compat.Io, gpa: std.mem.Allocator, path: []const u8, summary: *Summary) !void {
    const source = try compat.readFileAlloc(io, gpa, path, 8 * 1024 * 1024);
    defer gpa.free(source);
    summary.ptrcast_sites += countNeedle(source, "@ptrCast(");
    summary.aligncast_sites += countNeedle(source, "@alignCast(");
    summary.bitcast_sites += countNeedle(source, "@bitCast(");
}

fn countNeedle(hay: []const u8, needle: []const u8) usize {
    var n: usize = 0;
    var from: usize = 0;
    while (std.mem.indexOfPos(u8, hay, from, needle)) |idx| {
        n += 1;
        from = idx + needle.len;
    }
    return n;
}

pub fn writePolicy(
    writer: *std.Io.Writer,
    path: []const u8,
    summary: Summary,
    snap: baseline.Snapshot,
) std.Io.Writer.Error!void {
    try writer.writeAll("# myzig suggested policy (editable)\n\n");
    try writer.writeAll("Generated by `myzig adopt`. Edit freely.\n");
    try writer.writeAll("Ratchet uses `.myzig/baseline.json` via `myzig check --ratchet`.\n\n");
    try writer.print("## Scan path\n\n`{s}`\n\n", .{path});
    try writer.writeAll("## Project summary\n\n");
    try writer.print("- Zig files: {d}\n", .{summary.zig_files});
    try writer.print("- Ownership findings (current rules): {d}\n", .{snap.total_findings});
    try writer.print("- `@ptrCast(` sites (text count): {d}\n", .{summary.ptrcast_sites});
    try writer.print("- `@alignCast(` sites (text count): {d}\n", .{summary.aligncast_sites});
    try writer.print("- `@bitCast(` sites (text count): {d}\n\n", .{summary.bitcast_sites});

    try writer.writeAll("## Findings by rule (suggested soft budgets)\n\n");
    if (snap.by_rule.len == 0) {
        try writer.writeAll("_No findings - budget 0 for all rules._\n\n");
    } else {
        for (snap.by_rule) |rc| {
            try writer.print("- `{s}`: budget {d} (current)\n", .{ rc.rule_id, rc.count });
        }
        try writer.writeAll("\n");
    }

    try writer.writeAll("## Suggested posture\n\n");
    try writer.writeAll("- **default:** keep ordinary Zig first-class; fix ownership findings intentionally\n");
    try writer.writeAll("- **ratchet:** reject *increases* vs `.myzig/baseline.json` (`myzig check --ratchet`)\n");
    try writer.writeAll("- **prefer_compat:** optional — create `.myzig/prefer_compat` for `compat.volatile-std`\n");
    try writer.writeAll("- **unsafe-by-kind:** treat ptr/align/bit cast counts above as migration debt signals (not proofs)\n\n");
    try writer.writeAll("## Next steps\n\n");
    try writer.writeAll("1. Edit this file to record intent (what debt is accepted where).\n");
    try writer.writeAll("2. `myzig baseline` to refresh the ratchet snapshot after intentional cleanups.\n");
    try writer.writeAll("3. CI: `myzig check --ratchet <path>` so new debt fails the build.\n");
}

pub fn run(
    io: compat.Io,
    gpa: std.mem.Allocator,
    path: []const u8,
    myzig_version: []const u8,
    stdout: *std.Io.Writer,
    write_baseline_if_missing: bool,
) !void {
    try compat.createDirPath(io, ".myzig");

    const summary = try countTree(io, gpa, path);
    var result = try check_mod.checkPath(io, gpa, path);
    defer result.deinit(gpa);

    var snap = try baseline.fromDiagnostics(gpa, path, myzig_version, result.diagnostics.items);
    defer snap.deinit(gpa);

    var aw: std.Io.Writer.Allocating = .init(gpa);
    defer aw.deinit();
    try writePolicy(&aw.writer, path, summary, snap);
    try compat.writeFile(io, policy_path, aw.written());

    if (write_baseline_if_missing) {
        if (compat.access(io, baseline.baseline_path)) |_| {
            // keep existing baseline
        } else |_| {
            try baseline.writeFile(io, gpa, snap);
        }
    }

    try stdout.writeAll("myzig adopt\n\n");
    try stdout.print("Project summary ({s}):\n", .{path});
    try stdout.print("  {d} Zig files\n", .{summary.zig_files});
    try stdout.print("  {d} ownership findings\n", .{snap.total_findings});
    try stdout.print(
        "  unsafe-by-kind (text): ptrCast={d} alignCast={d} bitCast={d}\n\n",
        .{ summary.ptrcast_sites, summary.aligncast_sites, summary.bitcast_sites },
    );
    try stdout.writeAll("Findings by rule:\n");
    if (snap.by_rule.len == 0) {
        try stdout.writeAll("  (none)\n");
    } else {
        for (snap.by_rule) |rc| {
            try stdout.print("  {s}: {d}\n", .{ rc.rule_id, rc.count });
        }
    }
    try stdout.print("\nWrote editable policy: {s}\n", .{policy_path});
    if (write_baseline_if_missing) {
        try stdout.print("Baseline: {s} (created if missing)\n", .{baseline.baseline_path});
    }
    try stdout.writeAll("Suggestions are editable — never an irrevocable decree.\n");
}

test "countNeedle" {
    try std.testing.expect(countNeedle("a @ptrCast( x @ptrCast(", "@ptrCast(") == 2);
}
